[package]
name = "word-markov-gen"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0"
clap = "2.33.0"
rand = "0.6.5"
